#!/usr/bin/env bash
# detect-steering.sh — detect human steering for the vault-agent loop.
#
# Steering surface (single source of truth):
#   t20-vault-agent/main.md  — section "## Steering (user-editable)"
#
# This script reports STEERING only when that section has changed since
# the last vault-agent commit. Other vault diffs (session iter notes,
# dashboards regenerated by other loops, untracked project dirs) are
# reported as INFO — not as user instructions.
#
# Usage:
#   tools/detect-steering.sh            # full report
#   tools/detect-steering.sh --quiet    # only print if STEERING detected
#
# Exit:
#   0 — always (this is a probe, not a gate)

set -euo pipefail
cd "$(dirname "$0")/.."

QUIET=0
[[ "${1:-}" == "--quiet" ]] && QUIET=1

STEER_FILE="t20-vault-agent/main.md"
STEER_HEADING="## Steering (user-editable)"

LAST_VAULT_SHA=$(git log --author="vault-agent" -n 1 --format=%H 2>/dev/null || echo "")
if [[ -z "$LAST_VAULT_SHA" ]]; then
    LAST_VAULT_SHA=$(git rev-list --max-parents=0 HEAD)
fi

# Extract the Steering section from a file (or git ref:path) into stdout.
# Section runs from the heading line up to the next "---" or H2.
extract_steering() {
    awk -v heading="$STEER_HEADING" '
        $0 == heading { in_section = 1; next }
        in_section && /^---$/ { exit }
        in_section && /^## / { exit }
        in_section { print }
    '
}

CURRENT_SECTION=$(extract_steering < "$STEER_FILE" 2>/dev/null || true)
LAST_SECTION=$(git show "${LAST_VAULT_SHA}:${STEER_FILE}" 2>/dev/null | extract_steering || true)

# Strip whitespace-only lines and the boilerplate "_(empty — ...)_" line
# so that an unchanged-empty section reads as identical even with minor
# whitespace drift.
normalize() {
    sed -e '/^[[:space:]]*$/d' \
        -e '/^_(empty — no human steer/d'
}

CURRENT_NORM=$(echo "$CURRENT_SECTION" | normalize)
LAST_NORM=$(echo    "$LAST_SECTION"    | normalize)

if [[ "$CURRENT_NORM" == "$LAST_NORM" ]]; then
    [[ "$QUIET" -eq 1 ]] && exit 0
    echo "NO_STEERING — '${STEER_FILE}' Steering section unchanged since ${LAST_VAULT_SHA:0:7}"
else
    echo "=== HUMAN STEERING DETECTED ==="
    echo "Source: ${STEER_FILE} :: '${STEER_HEADING}'"
    echo "Diff vs ${LAST_VAULT_SHA:0:7}:"
    diff -u <(echo "$LAST_SECTION") <(echo "$CURRENT_SECTION") || true
    echo "STEERING:${STEER_FILE}"
fi

# In quiet mode we stop here. Full mode also reports INFO for other context.
[[ "$QUIET" -eq 1 ]] && exit 0

OTHER_CHANGED=$(git diff --name-only "$LAST_VAULT_SHA" -- ":(exclude)$STEER_FILE" 2>/dev/null || true)
OTHER_UNTRACKED=$(git ls-files --others --exclude-standard 2>/dev/null || true)

if [[ -n "$OTHER_CHANGED" || -n "$OTHER_UNTRACKED" ]]; then
    echo
    echo "=== INFO (not steering — other vault activity) ==="
    if [[ -n "$OTHER_CHANGED" ]]; then
        echo "## Tracked-file changes (other loops, vault-agent itself)"
        while IFS= read -r f; do
            [[ -z "$f" ]] && continue
            echo "INFO:changed:$f"
        done <<< "$OTHER_CHANGED"
    fi
    if [[ -n "$OTHER_UNTRACKED" ]]; then
        echo "## Untracked files (session iter notes, project dirs)"
        # Roll up to top-level dir to avoid spamming individual files
        echo "$OTHER_UNTRACKED" \
            | awk -F/ 'NF==1 {print; next} {print $1"/"}' \
            | sort -u \
            | while IFS= read -r f; do
                  [[ -z "$f" ]] && continue
                  echo "INFO:new:$f"
              done
    fi
fi

exit 0
